### ISSUE TITLE
future::makeClusterPSOCK behaves differently from parallel::makePSOCKcluster

### ISSUE THREAD

**Issue by nicolagnecco** [HenrikBengtsson/doFuture#53]
Hi,

I just moved from the `parallel` package to `future` package. I enjoy the package very much. 
At the same time, however, when I readapted my code, I observed the following two different behaviours.

For simplicity, let's say I create a three-node cluster (e.g., node 1, node 2 and node 3) and I have 12 tasks to perform (e.g., task 1, ..., task 12).

1. When I use `parallel::makePSOCKcluster` the tasks are allocated as follows: 
node 1: task 1, 
node 2: task 2, 
node 3: task 3, 
node 1: task 4, 
...
node 3: task 12.

When I use `future::makeClusterPSOCK`, the tasks are allocated as follows:
node 1: task 1, 
node 2: task 5, 
node 3: task 9, 
node 1: task 2, 
...
node 3: task 12.

Is it possible to achieve the same task allocation in `future::makeClusterPSOCK` as in `parallel::makePSOCKcluster`?

2. When I use `parallel::makePSOCKcluster`, there is a 'master' R process and several 'worker' R processes. If I kill the master process, then all the worker processes are also killed. However, with `future::makeClusterPSOCK`, killing the master R process leaves the worker processes running. Is this an intended behaviour? Probably, I am missing something simple here.

Thanks in advance for your support.
Best wishes,
Nicola

**Comment by HenrikBengtsson** [comment]
The difference you are observing is do to different "chunking" strategies.  Specifically,

1. `doFuture::registerDoFuture()` chunks by default
2. `doParallel::registerDoParallel(ncores)` chunks by default (only available on Linux and macOS)
3. `doParallel::registerDoParallel(cl = cl)` does not chunks by default

When processing in chunks ("chunking"), then the all _N_ iterations is chunked up into _W_ equally sized chunks (W = number of workers) and each worker process one chunk, which means there will be in total _W_ parallel jobs running.

Without chunking, each of the _N_ iterations is send individually to each of the _W_ workers, which means there will be in total _N_ parallel jobs running (but only _W_ at the same time).

Parallelization without chunking comes with more parallelization overhead, especially if there are lots of iterations to be done.  Because of this, chunking is often much more efficient.  This is why **doFuture**, **future.apply**, and **furrr** use chunking by default.


You can control whether or not chunking should take place in all three setups using specific `.options.*` arguments to `foreach()`;


## 1. doFuture (regardless of backend)

```r
library(foreach)
library(doFuture)
registerDoFuture()
plan(multisession, workers = 3)
## or equivalently
## cl <- parallel::makePSOCKcluster(3)
## plan(cluster, workers = cl)

# Default (use chunking)
y <- foreach(i=1:6, .combine=rbind) %dopar% {
  list(i = i, pid = Sys.getpid())
}
print(y)
#          i pid  
# result.1 1 19912
# result.2 2 19912
# result.3 3 19911
# result.4 4 19911
# result.5 5 19910
# result.6 6 19910

# Explicitly use chunking
y <- foreach(i=1:6, .combine=rbind, .options.future = list(scheduling = TRUE)) %dopar% {
  list(i = i, pid = Sys.getpid())
}
print(y)
#          i pid  
# result.1 1 19912
# result.2 2 19912
# result.3 3 19911
# result.4 4 19911
# result.5 5 19910
# result.6 6 19910

# Explicitly don't use chunking
y <- foreach(i=1:6, .combine=rbind, .options.future = list(scheduling = FALSE)) %dopar% {
  list(i = i, pid = Sys.getpid())
}
print(y)
#          i pid  
# result.1 1 19912
# result.2 2 19911
# result.3 3 19910
# result.4 4 19912
# result.5 5 19911
# result.6 6 19910
```


## 2. doParallel using forked parallelization (`doParallel:::doParallelMC()`)

This only works on Linux and macOS.  If tried on MS Windows, it'll fall back to case 3 below.

```r
library(foreach)
doParallel::registerDoParallel(ncores = 3)

# Default (use chunking)
y <- foreach(i=1:6, .combine=rbind) %dopar% {
  list(i = i, pid = Sys.getpid())
}
print(y)
#          i pid  
# result.1 1 21109
# result.2 2 21110
# result.3 3 21111
# result.4 4 21112
# result.5 5 21109
# result.6 6 21110

# Explicitly use chunking
y <- foreach(i=1:6, .combine=rbind, .options.multicore = list(preschedule = TRUE)) %dopar% {
  list(i = i, pid = Sys.getpid())
}
print(y)
#          i pid  
# result.1 1 21175
# result.2 2 21176
# result.3 3 21177
# result.4 4 21178
# result.5 5 21175
# result.6 6 21176

# Explicitly don't use chunking
y <- foreach(i=1:6, .combine=rbind, .options.multicore = list(preschedule = FALSE)) %dopar% {
  list(i = i, pid = Sys.getpid())
}
print(y)
#          i pid  
# result.1 1 21241
# result.2 2 21242
# result.3 3 21243
# result.4 4 21244
# result.5 5 21245
# result.6 6 21246
```

What the latter PIDs tell you is that when not using chunking, then each


## 3. doParallel using SNOW cluster parallelization (`doParallel:::doParallelSNOW()`)

```r
library(foreach)
cl <- parallel::makePSOCKcluster(3)
doParallel::registerDoParallel(cl = cl)

# Default (no chunking)
y <- foreach(i=1:6, .combine=rbind) %dopar% {
  list(i = i, pid = Sys.getpid())
}
print(y)
#          i pid  
# result.1 1 19912
# result.2 2 19911
# result.3 3 19910
# result.4 4 19912
# result.5 5 19911
# result.6 6 19910

# Explicitly don't use chunking
y <- foreach(i=1:6, .combine=rbind, .options.snow = list(preschedule = FALSE)) %dopar% {
  list(i = i, pid = Sys.getpid())
}
print(y)
#          i pid  
# result.1 1 19912
# result.2 2 19911
# result.3 3 19910
# result.4 4 19912
# result.5 5 19911
# result.6 6 19910

# Explicitly use chunking
y <- foreach(i=1:6, .combine=rbind, .options.snow = list(preschedule = TRUE)) %dopar% {
  list(i = i, pid = Sys.getpid())
}
print(y)
#          i pid  
# result.1 1 19912
# result.2 2 19912
# result.3 3 19911
# result.4 4 19911
# result.5 5 19910
# result.6 6 19910
```


You can read more about chunking in `?doParallel::registerDoParallel`, `?doFuture::doFuture` and `?future.apply::future_lapply` as well as in `?parallel::mclapply` and `?parallel::parLapply` (`chunk.size` in the latter).


# Postscript

It's very unfortunate that the **foreach** package itself does not define an option to control chunking, e.g. `foreach(..., scheduling = TRUE)`.  Instead, we have to use different arguments for different foreach adaptors, e.g. `.options.multicore`, `.options.snow`, and `.options.future`.  That makes it hard to write **foreach** that works regardless of which foreach adaptor the end-user registers.  This is one of a few unfortunate misfeatures that come with the **foreach** framework.  It can be fixed, but it has to be fixed by **foreach**.

**Comment by HenrikBengtsson** [comment]
For what's it's worth, see also Issue #48

**Comment by nicolagnecco** [comment]
First of all, thanks so much for such a clear and detailed explanation! This is extremely valuable to me since I have been spending quite a bit of time trying to understand parallel computation in R.
Now, I can also better see the great advantage of using `doFuture` compared to `doParallel`.

As a very last question, I see that in your example with `doParallel` with forked parallelization and no chunking, there are as many PIDs as tasks. Would this mean that there will be as many R sessions as tasks? I am sorry, but I cannot read your explanation after the example since it looks truncated.

Thanks again!

**Comment by HenrikBengtsson** [comment]
> ... in your example with doParallel with forked parallelization and no chunking, there are as many PIDs as tasks. Would this mean that there will be as many R sessions as tasks? I am sorry, but I cannot read your explanation after the example since it looks truncated.

Parallel processing via _forks_ is quite special.  There each future is a fork of the main R session with the main differences that it gets its own unique PID and `tempdir()`.  As soon as a forked workers (=one future) is finished, that forked worker process is terminated.  Next fork will get a new unique worker process and so on.   That is why you see different PIDs for each future (=worker).  In contrast, when using multisession (=PSOCK cluster workers), those workers are created only once so you'll see a fixed number of unique PIDs.

Now, the number of workers that are allowed to be running at the same time is given by `futures::nbrOfWorkers()`, which you specify via, say, `plan(multicore, workers = n)`.

**Comment by nicolagnecco** [comment]
Thanks again for all the help and the great packages!

**Comment by HenrikBengtsson** [comment]
You welcome
